data:
  f0_extractor: 'rmvpe'
  f0_min: 65
  f0_max: 800
  sampling_rate: 44100
  volume_smooth_size: 1024
  block_size: 512
  duration: 2
  encoder: 'contentvec768l12tta2x'
  cnhubertsoft_gate: 10
  encoder_sample_rate: 16000
  encoder_hop_size: 160
  encoder_out_channels: 768
  encoder_ckpt: pretrain/contentvec/pytorch_model.bin
  train_path: data/train
  valid_path: data/val
  extensions:
    - wav
model:
  type: 'RectifiedFlow'
  win_length: 2048
  n_aux_layers: 6
  n_aux_chans: 512
  n_layers: 6
  n_chans: 1024
  t_start: 0.0
  use_norm: true
  use_attention: false
  use_pitch_aug: true
  use_aux_f0: true
  use_f0_conditioning: false
  detach_ddsp_cond: true
  use_self_flow: true
  self_flow_mask_ratio: 0.5
  self_flow_condition_mask_ratio: 0.1
  self_flow_span_length: 5
  self_flow_loss_on_masked_only: false
  # ABLATION VARIABLE: Deeper student layer 3, teacher layer 5
  self_flow_student_layer: 3
  self_flow_teacher_layer: 5
  self_flow_projector_dim: 1024
  block_type: 'fused'
  gating_act: 'atan'
  n_spk: 1
device: cuda
vocoder:
  type: 'nsf-hifigan'
  ckpt: 'pretrain/nsf_hifigan/model'
infer:
  infer_step: 50
  method: 'euler'
env:
  expdir: exp/ablation-e2.3-layer-l3l5
  gpu_id: 0
train:
  num_workers: 2
  amp_dtype: fp16
  batch_size: 48
  cache_all_data: true
  cache_device: 'cpu'
  cache_fp16: true
  epochs: 100000
  interval_log: 1
  interval_val: 2000
  interval_force_save: 10000
  optimizer: 'muon'
  lr_scheduler: 'step'
  lr: 0.0005
  decay_step: 4000
  gamma: 0.9
  weight_decay: 0.1
  lambda_ddsp: 1
  lambda_f0: 0.1
  lambda_self_flow: 0.8
  save_opt: false
